
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/JY?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: ssk123456
    type: com.alibaba.druid.pool.DruidDataSource
    schema: classpath:/org/springframework/batch/core/schema-mysql.sql
    

  redis:
    host: 123
  batch:
    initialize-schema: always

